#- name: Tag and push to local registry
#  docker_image:
#     name: centos
#     repository: localhost:5000/centos
#     tag: 7
#     push: yes

---
- hosts: all
  vars:
    - ansible_python_interpreter: python2
  tasks:
#    - name: test task
#      shell: /usr/bin/touch cheese.txt || /bin/true
    - name: Build an image and push it to a private repo
      docker:
        path: ./sinatra
        name: registry.ansible.com/chouseknecht/sinatra
        tag: v1
        push: yes
